install:
  - chmod +x ./bin/texlive-install.sh
  - ./bin/texlive-install.sh
script:
  - chmod + x ./bin/build.sh
  - ./bin/build.sh
after_script:
  - chmod +x ./bin/upload.sh
  - chmod +x ./bin/gdrive
  - ./bin/upload.sh
