sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german texlive-math-extra
script:
- mkdir _build/2017WS/ANA3/ _build/2017WS/NUM/
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build/2017WS/ANA3/ 2017WS/ANA3/UE04/ana3-ue04.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build/2017WS/NUM/ 2017WS/NUM/UE06/num-ue06.tex
after_script:
- ./bin/upload.sh
