sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german texlive-math-extra
script:
- mkdir _build _build/2017WS _build/2017WS/ANA3/ _build/2017WS/NUM/
- cd 2017WS/ANA3/UE04
- pdflatex -interaction=nonstopmode -halt-on-error ana3-ue04.tex
- cp ana3-ue04.pdf ../../../_build/2017WS/ANA3
- cd ../../..
- cd 2017WS/NUM/UE06
- pdflatex -interaction=nonstopmode -halt-on-error num-ue06.tex
- cp num-ue06.pdf ../../../_build/2017WS/NUM
- cd ../../..
after_script:
- chmod +x ./bin/upload.sh
- chmod +x ./bin/gdrive
- ./bin/upload.sh
